/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":model"))
    implementation("com.github.freva:ascii-table:1.8.0")
    implementation("com.athaydes.rawttp:rawttp")
}
